# Generated by Django 3.0.8 on 2020-07-06 22:12

from django.db import migrations

from datetime import date

def add_initial_classes_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Aula = apps.get_model('aulas', 'Aula')
    initial_data = [{
        "titulo": "Full Cycle e Estudo de caso",
        "data_lancamento": date(2020, 6, 29)
    }, {
        "titulo": "Microsserviço de assinaturas com RabbitMQ e Golang Buffalo",
        "data_lancamento": date(2020, 6, 30)
    }, {
        "titulo": "Serverless framework e processamento de pagamentos",
        "data_lancamento": date(2020, 7, 1)
    }, {
        "titulo": "Multi-tenancy applications com Django",
        "data_lancamento": date(2020, 7, 2)
    }, {
        "titulo": "Ecommerce com Nest.js, Loopback e ElasticSearch",
        "data_lancamento": date(2020, 7, 3)
    }, {
        "titulo": "Microsserviços com Docker e Kubernetes",
        "data_lancamento": date(2020, 7, 5)
    }]

    for data in initial_data:
        Aula.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_classes_data)
    ]
